version: '26.1'

services:
  app:
    image: your-spring-boot-app-image
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/register
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: summer2024
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: summer2024
      POSTGRES_DB: register
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: